site_name: Wall v0.1
site_description: Event-driven Wall-building simulator
site_author: Wall Demo Team

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight

nav:
  - Home: index.md
  - API Reference: api-reference.md
  - Simulator: simulator.md
  - Database Connection: database-connections.md
  - Api Gateway: api-gateway.md

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true
