# Generated by Django 5.2.4 on 2025-07-09 15:31

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallprofile",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for the wall profile",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
