# Generated by Django 5.2.4 on 2025-07-09 16:19

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_wallprofile_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskWallProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the wall profile",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the wall profile",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_day", models.PositiveIntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "task_wall_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WallSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "section_index",
                    models.PositiveIntegerField(
                        help_text="0-based index of section within profile"
                    ),
                ),
                (
                    "initial_height",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Initial height in feet (0-30)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("30")),
                        ],
                    ),
                ),
                (
                    "current_height",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current height in feet",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("30")),
                        ],
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="profiles.taskwallprofile",
                    ),
                ),
            ],
            options={
                "db_table": "wall_sections",
                "ordering": ["profile", "section_index"],
                "unique_together": {("profile", "section_index")},
            },
        ),
    ]
