# Generated by Django 5.2.4 on 2025-07-09 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_taskwallprofile_wallsection"),
    ]

    operations = []
